Enabling Advanced Logging
vmfarms/terraform-aws-elasticsearch pull request #12
Opened 2020-11-24 17:23 UTC by daniel-araya5813

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # https://github.com/vmfarms/terraform-aws-elasticsearch/issues/11

# Checklist:

- [ ] Update the changelog with any notable changes such as features added, changed, fixed, and/or removed.
- [ ] I have made corresponding changes to the documentation

2020-11-24 17:24 UTC, daniel-araya5813 commented
Sandbox main.tf config

```
module "elasticsearch" {
  source                    = "app.terraform.io/vmfarms/elasticsearch/aws"
  version                   = "0.3.0"
  domain                    = "sandbox-advanced-logging"
  elasticsearch_version     = "7.4"
  instance_count            = "2"
  instance_type             = "t3.medium.elasticsearch"
  private_subnets           = module.vpc.private_subnets
  private_subnets_cidrs     = ["10.0.0.0/16"]
  region                    = local.region
  volume_size               = "50"
  log_publishing_options    = true
  domain_endpoint_options   = true
  advanced_security_options = true
  cognito_options           = true
  master_user_options       = false
 # log_type                 = ["INDEX_SLOW_LOGS", "SEARCH_SLOW_LOGS", "ES_APPLICATION_LOGS", "AUDIT_LOGS"]
 # cloudwatch_log_group_arn = "arn:aws:logs:us-east-1:481318636172:log-group:elasticsearch-logs:*"
  vpc_id                    = module.vpc.vpc_id
}
```

2020-11-24 20:08 UTC, daniel-araya5813 commented
Sandbox branch "es-logs"

2020-11-25 18:12 UTC, ec209 requested changes

2020-11-25 18:12 UTC, ec209 commented on main.tf
> +data "aws_iam_policy_document" "elasticsearch-log-publishing-policy" {
I have a general question, is this module works with the VPC based ES? 
I think ES in the vpc requires some more configurations : https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain

2020-11-25 18:12 UTC, ec209 commented on variables.tf
> +variable "log_type_index_slow_logs" {
Basis on this: https://github.com/sreenivasyanamala/terraform-es/tree/469c86ea6336be1253d6f4ab73a3a752c331af94/elastic-search
, i believe we can create a map type variable and feed values to for_loop

2020-11-25 18:37 UTC, dpolitiuk commented on main.tf
> +    tls_security_policy      = "Policy-Min-TLS-1-2-2019-07"
I assume the `Policy-Min-TLS-1-0-2019-07` refers to TLS 1.0 while the `Policy-Min-TLS-1-2-2019-07` refers to TLS 1.2. If my assumption is correct I see no reason to consider the lower version. The only valid case would be compatibility reason, which we should tackle if/when we encounter it.

2020-11-26 21:11 UTC, daniel-araya5813 commented on main.tf
> +  log_publishing_options {
Each option incurs a cost, so I think it's important to leave each option configurable individually in case the client decides to only enable one of the advance logging options.

2020-11-26 21:16 UTC, daniel-araya5813 commented on main.tf
> +  retention_in_days = "0"
I've changed the retention days to 30

2020-11-26 21:20 UTC, daniel-araya5813 commented on main.tf
> +data "aws_iam_policy_document" "elasticsearch-log-publishing-policy" {
I was able to build an elasticsearch domain with this set-up. You can see it here https://console.aws.amazon.com/es/home?region=us-east-1#

2020-12-01 22:39 UTC, osdemah commented
This PR includes some unnecessary changes which we were not looking into!

2020-12-01 22:39 UTC, closed without merging